package secure

import (
	"testing"
)

func TestDecryptNodeAESGCMFormat(t *testing.T) {
	secret := "a-long-test-secret"
	// Generated by shared/src/secure.js with a fixed 12-byte IV.
	encoded := "313233343536373839303132:630270ef3cef4085564ab65d9f806393:a79971b57e2d5d341c"

	decrypter, err := NewDecrypter(secret)
	if err != nil {
		t.Fatal(err)
	}
	got, err := decrypter.Decrypt(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if got != "sensitive" {
		t.Fatalf("got %q", got)
	}
}

func TestEncryptRoundTrip(t *testing.T) {
	cipher, err := NewDecrypter("a-long-test-secret")
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := cipher.Encrypt(`{"amount":16.4}`)
	if err != nil {
		t.Fatal(err)
	}
	got, err := cipher.Decrypt(encoded)
	if err != nil {
		t.Fatal(err)
	}
	if got != `{"amount":16.4}` {
		t.Fatalf("got %q", got)
	}
}
