[Unit]
Requires=kwmembership-xvfb.service
After=kwmembership-xvfb.service

[Service]
Environment=DISPLAY=:99
Environment=KWMEMBERSHIP_VISIBLE_BROWSER=true
Environment=KWMEMBERSHIP_CHROME_PROXY_SERVER=http://127.0.0.1:7890
BindReadOnlyPaths=/tmp/.X11-unix
